# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: ""
url: ""
timezone: Asia/Shanghai
date_format: "ordinal"
title: 代码的回声
author: ""
paginate: 15

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /feed.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: redcarpet
redcarpet: 
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]
pygments: true
permalink: /:year/:month/:day/:title
include:
    - _redirects
exclude:
    - functions
    - _scripts
    - wrangler.toml
    - node_modules
    - Gemfile
    - Gemfile.lock
    - README.md
    - README.textile
    - LICENSE
    - AGENTS.md
    - .travis.yml
    - _config_cf.yml
gems:
    - jekyll-sitemap
    - jekyll-gist
    - jekyll-paginate