# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: http://assertion.github.io
url: http://assertion.github.io
date_format: "ordinal"
title: Aaren Xia
author: Aaren Xia 
paginate: 9

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /atom.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: redcarpet
redcarpet: 
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]
pygments: true
permalink: /:year/:month/:day/:title
gems:
    - jekyll-sitemap
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
duoshuo_short_name: mazhuang

# ---------------- #
#      Adsense     #
# ---------------- #
adsense: true
amazon: false
